apiVersion: v2
name: medusa-store
description: A Helm chart for Medusa Store
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: 17.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
