apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-medusa
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx

  rules:
    - host: {{ printf "%s.127.0.0.1.nip.io" .Release.Name }}
      http:
        paths:

          - path: /store(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-medusa-api
                port:
                  number: 80

          - path: /admin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-medusa-api
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-storefront
                port:
                  number: 3000
