apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medusa-api
  namespace: {{ .Release.Namespace }}

spec:
  type: ClusterIP

  selector:
    app: {{ .Release.Name }}-medusa-api

  ports:
    - name: http
      port: 80
      targetPort: 9000
